{
 "title": "Game Inspect",
 "time": { "from": "now-3d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "game_id",
    "label": "Game",
    "query": "PUBG BATTLEGROUNDS : 578080, Counter-Strike 2 : 730, \t\nELDEN RING : 1245620, Black Myth Wukong : 2358720, Palworld : 1623730, Monster Hunter Wilds : 2246340, Lost Ark : 1599340, \t\nCyberpunk 2077 : 1091500"
   }
  ]
 },
 "panels": [
  {
   "title": "Last Player Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "collection": "player_stats_30min",
     "queryText": "[\r\n  { \r\n    \"$match\": { \r\n      \"$and\": [\r\n        {\r\n          \"$expr\": {\r\n            \"$eq\": [\"$app_id\", { \"$toInt\": \"$game_id\" }]\r\n          }\r\n        }\r\n      ]\r\n    } \r\n  },\r\n  { \"$sort\": { \"window_start\": 1 } },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 0,\r\n      \"time\": \"$window_start\",\r\n      \"Peak\": \"$max_players\",\r\n      \"Average\": \"$avg_players\"\r\n    }\r\n  }\r\n]"
    }
   ]
  },
  {
   "title": "Player Count Trend",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "collection": "player_stats_30min",
     "queryText": "[\r\n  { \r\n    \"$match\": { \r\n      \"$expr\": {\r\n        \"$eq\": [\"$app_id\", { \"$toInt\": \"$game_id\" }]\r\n      }\r\n    } \r\n  },\r\n  { \"$sort\": { \"window_start\": 1 } },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 0,\r\n      \"time\": \"$window_start\",\r\n      \"Peak Players\": \"$max_players\"\r\n    }\r\n  }\r\n]"
    }
   ]
  },
  {
   "title": "Total Reviews",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "collection": "reviews_hourly",
     "queryText": "[\r\n  { \r\n    \"$match\": { \r\n      \"app_id\": \"$game_id\"\r\n    } \r\n  },\r\n  {\r\n    \"$group\": {\r\n      \"_id\": null,\r\n      \"value\": { \"$sum\": \"$total_reviews\" }\r\n    }\r\n  },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 0,\r\n      \"value\": 1\r\n    }\r\n  }\r\n]"
    }
   ]
  },
  {
   "title": "Negative vs Positive Reviews",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "collection": "reviews_hourly",
     "queryText": "[\r\n  { \r\n    \"$match\": { \r\n      \"app_id\": \"$game_id\"\r\n    } \r\n  },\r\n  {\r\n    \"$group\": {\r\n      \"_id\": null,\r\n      \"Positive\": { \"$sum\": \"$positive_count\" },\r\n      \"Negative\": { \"$sum\": \"$negative_count\" }\r\n    }\r\n  },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 0,\r\n      \"Positive\": 1,\r\n      \"Negative\": 1\r\n    }\r\n  }\r\n]"
    }
   ]
  },
  {
   "title": "Positive/Negative Reviews Trend",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 9 },
   "targets": [
    {
     "collection": "reviews_hourly",
     "queryText": "[\r\n  { \r\n    \"$match\": { \r\n      \"app_id\": \"$game_id\"\r\n    } \r\n  },\r\n  { \"$sort\": { \"window_start\": 1 } },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 0,\r\n      \"time\": \"$window_start\",\r\n      \"Positive\": \"$positive_count\",\r\n      \"Negative\": \"$negative_count\"\r\n    }\r\n  }\r\n]"
    }
   ]
  }
 ]
}