{
 "title": "Steam Lens",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Games",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "collection": "game_fact",
     "queryText": "[\r\n  {\r\n    \"$group\": {\r\n      \"_id\": \"$name\" \r\n    }\r\n  },\r\n  {\r\n    \"$count\": \"value\"\r\n  }\r\n]"
    }
   ]
  },
  {
   "title": "Average Price",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "collection": "game_fact",
     "queryText": "[\r\n  {\r\n    \"$group\": {\r\n      \"_id\": \"$name\",\r\n      \"game_price\": { \"$max\": \"$final_price\" }\r\n    }\r\n  },\r\n  {\r\n    \"$group\": {\r\n      \"_id\": null,\r\n      \"value\": { \"$avg\": \"$game_price\" }\r\n    }\r\n  }\r\n]"
    }
   ]
  },
  {
   "title": "Most Popular Genres",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 0 },
   "targets": [
    {
     "collection": "game_genre",
     "queryText": "[\r\n  {\r\n    \"$match\": {\r\n      \"genre\": { \"$ne\": \"\", \"$exists\": true }\r\n    }\r\n  },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 0,\r\n      \"Genre\": \"$genre\",\r\n      \"Game Count\": \"$total_games\"\r\n    }\r\n  },\r\n  { \"$sort\": { \"Game Count\": -1 } },\r\n  { \"$limit\": 10 }\r\n]"
    }
   ]
  },
  {
   "title": "Most Hated Games (Negative/Total Reviews)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 15, "y": 0 },
   "targets": [
    {
     "collection": "game_fact",
     "queryText": "[\r\n  {\r\n    \"$group\": {\r\n      \"_id\": \"$name\",\r\n      \"pos\": { \"$max\": \"$positive_reviews\" },\r\n      \"neg\": { \"$max\": \"$negative_reviews\" }\r\n    }\r\n  },\r\n  {\r\n    \"$addFields\": {\r\n      \"total_feedback\": { \"$add\": [\"$pos\", \"$neg\"] }\r\n    }\r\n  },\r\n  {\r\n    \"$match\": {\r\n      \"total_feedback\": { \"$gte\": 50000 }\r\n    }\r\n  },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 0,\r\n      \"game\": \"$_id\",\r\n      \"Disapproval Rate\": { \"$divide\": [\"$neg\", \"$total_feedback\"] }\r\n    }\r\n  },\r\n  { \"$sort\": { \"Disapproval Rate\": -1 } },\r\n  { \"$limit\": 5 }\r\n]"
    }
   ]
  },
  {
   "title": "Total Developers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "collection": "game_dev",
     "queryText": "[\r\n  {\r\n    \"$group\": {\r\n      \"_id\": \"$developer\" \r\n    }\r\n  },\r\n  {\r\n    \"$count\": \"value\"\r\n  }\r\n]"
    }
   ]
  },
  {
   "title": "Games Released and Developers Active Each Year",
   "type": "trend",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "collection": "release_trend",
     "queryText": "[\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 0,\r\n      \"Year\": \"$release_year\",\r\n      \"Games Released\": \"$total_games\",\r\n      \"Active Developers\": { \"$size\": { \"$ifNull\": [\"$developers_active\", []] } }\r\n    }\r\n  },\r\n  { \"$sort\": { \"Year\": 1 } }\r\n]"
    }
   ]
  },
  {
   "title": "Price Segments Comparison",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 9 },
   "targets": [
    {
     "collection": "price_segment",
     "queryText": "[\r\n  {\r\n    \"$match\": {\r\n      \"price_segment\": { \"$ne\": \"Unknown\" }\r\n    }\r\n  },\r\n  {\r\n    \"$addFields\": {\r\n      \"CleanSegment\": {\r\n        \"$cond\": {\r\n          \"if\": { \"$eq\": [\"$price_segment\", \"Other\"] },\r\n          \"then\": \"0-9.99\",\r\n          \"else\": \"$price_segment\"\r\n        }\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 0,\r\n      \"Segment\": \"$CleanSegment\",\r\n      \"Games\": \"$total_games\",\r\n      \"Avg Playtime (hour)\": \"$avg_playtime\",\r\n      \"Avg Positive Reviews \": \"$avg_positive_reviews\"\r\n    }\r\n  },\r\n  { \"$sort\": { \"Segment\": 1 } }\r\n]"
    }
   ]
  },
  {
   "title": "Most Played Games (By total hours)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 17 },
   "targets": [
    {
     "collection": "game_fact",
     "queryText": "[\r\n  { \r\n    \"$match\": { \r\n      \"playtime_total\": { \"$gt\": 0 } \r\n    } \r\n  },\r\n  {\r\n    \"$group\": {\r\n      \"_id\": \"$name\",\r\n      \"max_playtime\": { \"$max\": \"$playtime_total\" }\r\n    }\r\n  },\r\n  { \"$sort\": { \"max_playtime\": -1 } },\r\n  { \"$limit\": 10 },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 0,\r\n      \"game\": \"$_id\",\r\n      \"playtime\": \"$max_playtime\"\r\n    }\r\n  }\r\n]"
    }
   ]
  },
  {
   "title": "Most Expensive Games ",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "collection": "game_fact",
     "queryText": "[\r\n  { \r\n    \"$match\": { \r\n      \"final_price\": { \"$gt\": 0 } \r\n    } \r\n  },\r\n  {\r\n    \"$group\": {\r\n      \"_id\": \"$name\",\r\n      \"highest_price\": { \"$max\": \"$final_price\" }\r\n    }\r\n  },\r\n  { \"$sort\": { \"highest_price\": -1 } },\r\n  { \"$limit\": 10 },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 0,\r\n      \"game\": \"$_id\",\r\n      \"price\": \"$highest_price\"\r\n    }\r\n  }\r\n]"
    }
   ]
  }
 ]
}