---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: frostedpilot/graphana:latest
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: Admin
            - name: GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS
              value: grafana-mongodb-opensource-datasource,trino-datasource
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: datasource-storage
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
            - name: dashboard-storage
              mountPath: /etc/grafana/provisioning/dashboards
              readOnly: true
            - name: grafana-storage
              mountPath: /var/lib/grafana
      securityContext:
        fsGroup: 472
        runAsUser: 472
        runAsNonRoot: true
      nodeSelector:
        device: ngo
      volumes:
        - name: datasource-storage
          configMap:
            name: grafana-datasource
        - name: dashboard-storage
          emptyDir: {}
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: grafana