apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: monitoring
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: MongoDB
        uid: mongodb-ds
        type: grafana-mongodb-opensource-datasource
        access: proxy
        url: http://localhost:3333
        isDefault: true
        jsonData:
          mongodb_url: "mongodb://root:password@my-mongodb.database.svc.cluster.local:27017/?authSource=admin&directConnection=true"
          mongodb_db: "steam_analytics"
        editable: true

      - name: Prometheus
        uid: prometheus-ds
        type: prometheus
        access: proxy
        url: http://prometheus.monitoring.svc.cluster.local:9090
        isDefault: false
        editable: true

      - name: Trino
        uid: trino-ds
        type: trino-datasource
        access: proxy
        url: http://trino.default.svc.cluster.local:8080
        isDefault: false
        editable: true
