---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: Admin
            - name: GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS
              value: haohanyang-mongodb-datasource #"meln5674-mongodb-community"
            - name: GF_INSTALL_PLUGINS
              value: "https://github.com/haohanyang/mongodb-datasource/releases/download/v0.5.0-alpha.2/haohanyang-mongodb-datasource-0.5.0-alpha.2.zip;haohanyang-mongodb-datasource" #"https://github.com/meln5674/grafana-mongodb-community-plugin/releases/latest/download/meln5674-mongodb-community.zip;meln5674-mongodb-community"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: datasource-storage
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
            - name: dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards
              readOnly: true
            - name: dashboard-storage
              mountPath: /var/lib/grafana/provisioning/dashboards
              readOnly: true
            - name: grafana-storage
              mountPath: /var/lib/grafana
      securityContext:
        fsGroup: 472
        runAsUser: 472
        runAsNonRoot: true
      nodeSelector:
        device: ngo
      volumes:
        - name: datasource-storage
          configMap:
            name: grafana-datasource
        - name: dashboard-provider
          configMap:
            name: grafana-dashboard-provider
        - name: dashboard-storage
          configMap:
            name: grafana-dashboards
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: grafana