apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - grafana.yml
  - provisioning/dashboard-provider-configmap.yaml
  - provisioning/grafana-datasource-configmap.yaml
  - prometheus-deployment.yml
  - prometheus-configmap.yml
  - kafka-exporter.yml
  - mongodb-exporter.yml
  - mongodb-express.yaml
