apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: monitoring
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: MongoDB
        uid: mongodb-ds
        type: "haohanyang-mongodb-datasource"
        access: proxy
        url: mongodb://my-mongodb.database.svc.cluster.local:27017
        isDefault: true
        jsonData:
          host: my-mongodb.database.svc.cluster.local:27017
          database: steam_analytics
          authMethod: Username/Password
          authDatabase: admin
          directConnection: true
          tlsEnabled: false
          username: root
        secureJsonData:
          password: password
        editable: true

      - name: Prometheus
        uid: prometheus-ds
        type: prometheus
        access: proxy
        url: http://prometheus.monitoring.svc.cluster.local:9090
        isDefault: false
        editable: true